apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: sniphub
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: ZGVkZWRlZGVkZWRldmdyZ3RqZ2sK

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: sniphub

  labels:
    app: postgres
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: sniphub
  labels:
    app: postgres
spec:
  storageClassName: default
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: sniphub
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12
        envFrom:
        - configMapRef:
            name: postgres-config
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim
--- 
apiVersion: v1
kind: Service
metadata:
  name: postgres-statefulset
  namespace: sniphub
  labels:
    app: postgres-statefulset
spec:
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-statefulset