apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-port-forward
  namespace: sniphub

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-port-forward
  namespace: sniphub
rules:
- apiGroups: [""]
  resources: ["services"]
  resourceNames: ["postgres-statefulset"]
  verbs: ["get"]

- apiGroups: [""]
  resources: ["pods"]
  resourceNames: ["postgres-statefulset-0"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["services/podforward"]
  resourceNames: ["postgres-statefulset"]
  verbs: ["create"]

- apiGroups: [""]
  resources: ["pods/portforward"]
  resourceNames: ["postgres-statefulset-0"]
  verbs: ["create"]

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-port-forward
  namespace: sniphub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-port-forward
subjects:
- kind: ServiceAccount
  name: postgres-port-forward
  namespace: sniphub