apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cluster
  namespace: istio-system
spec:
  acme:
    email: mathis.deconchat@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-cluster
    solvers:
    - http01:
        ingress:
          class: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sniphub-cert-production
  namespace: istio-system
spec:
  secretName: sniphub-cert-production
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "sniphub.darmanin.info" # For demo purposes
  issuerRef:
    name: letsencrypt-prod-cluster
    kind: ClusterIssuer
    group: cert-manager.io
--- 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sniphub-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - 'sniphub.darmanin.info'
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - 'sniphub.darmanin.info'
    tls:
      mode: SIMPLE
      credentialName: sniphub-cert-production