---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sniphub-front
  namespace: sniphub
spec:
  selector:
    matchLabels:
      app: sniphub-front
  replicas: 3
  template:
    metadata:
      labels:
        app: sniphub-front
        namespace: sniphub
    spec:
      containers:
        - name: sniphub-front
          image: registry.digitalocean.com/docker-cours/sniphub-front:main-eb36a518fafc3e4fbded5b1c950143f3692c6dcc
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: REACT_APP_API_URL
              value: "http://sniphub-back:4000"
          # securityContext:  
          #   allowPrivilegeEscalation: false
