---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sniphub-front
  namespace: sniphub
spec:
  selector:
    matchLabels:
      app: sniphub-front
  replicas: 3
  template:
    metadata:
      labels:
        app: sniphub-front
        namespace: sniphub
        snip-auth: "true"
    spec:
      securityContext:
        runAsUser: 101
      containers:
        - name: sniphub-front
          image: registry.digitalocean.com/docker-cours/sniphub-front:main-f65bff89fb7f7d26587e3ef11c95726b2d7b923f
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: REACT_APP_API_URL
              value: "http://sniphub-back:4000"
          securityContext:
            capabilities:
              drop:
                - NET_RAW
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - emptyDir: {}
          name: tmp
