apiVersion: apps/v1
kind: Deployment
metadata:
  name: sniphub-front
  namespace: sniphub
spec:
  selector:
    matchLabels:
      app: sniphub-front
  replicas: 3
  template:
    metadata:
      labels:
        app: sniph-front
        namespace: sniphub
    spec:
      containers:
      - name: sniph-front
        image: registry.digitalocean.com/docker-cours/sniphub-front:main-11
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "http://sniphub-back:4000"

---
apiVersion: v1
kind: Service  
metadata:
  name: sniphub-front
  namespace: sniphub
spec:
  selector:
    app: sniphub-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sniphub-front
spec:
  hosts:
  - "sniphub.darmanin.info"
  http:
  - match:
    - uri:
        prefix: /
  - route:
    - destination:
        host: sniphub-front
        subset: v1
--- 

