apiVersion: v1
kind: Secret
metadata:
  name: sniphub-back
  namespace: sniphub
stringData:
  DATABASE_URL: postgresql://admin:ZGVkZWRlZGVkZWRldmdyZ3RqZ2sK@postgres-statefulset.sniphub.svc.cluster.local:5432/postgresdb
