
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sniphub-back
  namespace: sniphub
spec:
  selector:
    matchLabels:
      app: sniphub-back
  replicas: 3
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: sniphub-back
        namespace: sniphub
        snip-auth: "true"
    spec:
      containers:
        - name: sniphub-back
          image: registry.digitalocean.com/docker-cours/sniphub-back:main-2452d4751a62eee38f441ad9170dcdad7346f1a2
          ports:
            - containerPort: 4000
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sniphub-back
                  key: DATABASE_URL
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - sniphub-back
              topologyKey: "kubernetes.io/hostname"
