---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sniphub-back
  namespace: sniphub
spec:
  selector:
    matchLabels:
      app: sniphub-back
  replicas: 3
  template:
    metadata:
      labels:
        app: sniphub-back
        namespace: sniphub
    spec:
      containers:
        - name: sniphub-back
          image: registry.digitalocean.com/docker-cours/sniphub-back:main-ab9cd26c7175e302954d747152d2d91afa3d9b24
          ports:
            - containerPort: 4000
              name: http
          env:
            - name: DATABASE_URL
              value: postgresql://admin:ZGVkZWRlZGVkZWRldmdyZ3RqZ2sK@postgres-statefulset.sniphub.svc.cluster.local:5432/postgresdb
