---
apiVersion: v1
kind: Service
metadata:
  name: sniphub-back
  namespace: sniphub
spec:
  selector:
    app: sniphub-back
  ports:
    - name: http
      port: 4000
      targetPort: 4000

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sniphub-back
  namespace: sniphub
spec:
  hosts:
  - "sniphub.darmanin.info"
  gateways:
  - sniphub-gateway
  http:
  - match:
    - uri:
        prefix: /graphql
    rewrite:
      uri: '/graphql'
    route:
    - destination:
        host: sniphub-back
        port:
          number: 4000
---