apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sniphub-back
  namespace: sniphub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sniphub-back
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50