name: Repository Dispatch Back

on:
  repository_dispatch:
    types: [new-image-back]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:

      contents: write
    steps:
    - uses: actions/checkout@v2

    - name: Update Image Version
      id: imgupd
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i sniphub-back/02_nest.yaml
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes